[tool.pydocstyle]
convention = "google"
add-ignore = [
  "D100", # Missing docstring in public module
  "D104", # Missing docstring in public package
]

[tool.mypy]
python_version = "3.11"
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
disallow_untyped_defs = true
no_implicit_optional = true
pretty = true
ignore_missing_imports = true
# You can add per-module ignores here if needed, e.g. for 3rd-party stubs
# [[tool.mypy.overrides]]
# module = ["ddgs.*"]
# ignore_missing_imports = true
