name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff==0.6.2
          pip install pre-commit==3.8.0

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Pre-commit (mypy, pydocstyle)
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Byte-compile (sanity check)
        run: |
          python -m compileall .
